
import java.awt.Image;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author ahmed
 */
public class Softwarepage extends javax.swing.JFrame {
    
    public Softwarepage() {
        initComponents();
        
        Image img =new ImageIcon(this.getClass().getResource("/logo.jpg")).getImage();
         this.setIconImage(img);
            try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con =DriverManager .getConnection("jdbc:mysql://localhost:3306/hotel2","root","root");
            
        } catch (ClassNotFoundException ex) {   
            JOptionPane.showMessageDialog(this, "Connection failed");
        } catch (SQLException ex) {
           JOptionPane.showMessageDialog(this, "Connection failed");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 32767));
        jPanel1 = new javax.swing.JPanel();
        SW_list = new javax.swing.JButton();
        SW_book = new javax.swing.JButton();
        SW_return = new javax.swing.JButton();
        SW_view = new javax.swing.JButton();
        SW_explore = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu Page");
        setIconImages(null);
        setPreferredSize(new java.awt.Dimension(1320, 740));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setForeground(new java.awt.Color(0, 0, 0));

        SW_list.setBackground(new java.awt.Color(0, 0, 0));
        SW_list.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        SW_list.setForeground(new java.awt.Color(255, 255, 255));
        SW_list.setText("View All Rooms");
        SW_list.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SW_listActionPerformed(evt);
            }
        });

        SW_book.setBackground(new java.awt.Color(204, 102, 0));
        SW_book.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        SW_book.setForeground(new java.awt.Color(255, 255, 255));
        SW_book.setText("Book now");
        SW_book.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SW_bookActionPerformed(evt);
            }
        });

        SW_return.setBackground(new java.awt.Color(0, 0, 0));
        SW_return.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        SW_return.setForeground(new java.awt.Color(255, 255, 255));
        SW_return.setText("Home ");
        SW_return.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SW_returnActionPerformed(evt);
            }
        });

        SW_view.setBackground(new java.awt.Color(0, 0, 0));
        SW_view.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        SW_view.setForeground(new java.awt.Color(255, 255, 255));
        SW_view.setText("List booking");
        SW_view.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SW_viewActionPerformed(evt);
            }
        });

        SW_explore.setBackground(new java.awt.Color(0, 0, 0));
        SW_explore.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        SW_explore.setForeground(new java.awt.Color(255, 255, 255));
        SW_explore.setText("Explore Rooms");
        SW_explore.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SW_exploreActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\ahmed\\OneDrive\\Desktop\\download.jpg.png")); // NOI18N

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\ahmed\\Downloads\\download (1).png")); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(SW_book, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(SW_return, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(SW_list)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(SW_view, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(SW_explore, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(SW_return, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SW_list, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SW_view, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SW_explore, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SW_book, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addContainerGap(75, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SW_returnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SW_returnActionPerformed
        // TODO add your handling code here:
        KOKO_Hotel KOKO_HotelFrame =  new KOKO_Hotel();
        KOKO_HotelFrame.setVisible(true);
        KOKO_HotelFrame.setLocationRelativeTo(null);//center
        this.dispose();
    }//GEN-LAST:event_SW_returnActionPerformed

    private void SW_listActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SW_listActionPerformed
        // TODO add your handling code here:
        View_All_Room View_All_RoomFrame =  new View_All_Room();
        View_All_RoomFrame.setVisible(true);
        View_All_RoomFrame.setLocationRelativeTo(null);//center
        this.dispose();
    }//GEN-LAST:event_SW_listActionPerformed

    private void SW_viewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SW_viewActionPerformed

        // TODO add your handling code here:
        List_of_Booking List_of_BookingFrame =  new List_of_Booking();
        List_of_BookingFrame.setVisible(true);
        List_of_BookingFrame.setLocationRelativeTo(null);//center
        this.dispose();
    }//GEN-LAST:event_SW_viewActionPerformed

    private void SW_bookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SW_bookActionPerformed
        // TODO add your handling code here:
        Book_Room Book_RoomFrame =  new Book_Room();
        Book_RoomFrame.setVisible(true);
        Book_RoomFrame.setLocationRelativeTo(null);//center
        this.dispose();
    }//GEN-LAST:event_SW_bookActionPerformed

    private void SW_exploreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SW_exploreActionPerformed
        // TODO add your handling code here:

        Explore_Rooms Explore_RoomsFrame =  new Explore_Rooms();
        Explore_RoomsFrame.setVisible(true);
        Explore_RoomsFrame.setLocationRelativeTo(null);//center
        this.dispose();
    }//GEN-LAST:event_SW_exploreActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Softwarepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Softwarepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Softwarepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Softwarepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Softwarepage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton SW_book;
    private javax.swing.JButton SW_explore;
    private javax.swing.JButton SW_list;
    private javax.swing.JButton SW_return;
    private javax.swing.JButton SW_view;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
